### PR TITLE
[wip] restore tests commented out for pypy37 migration

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- doesn't need to be merged/shipped (just restores tests)
- can help verify https://github.com/conda-forge/ipykernel-feedstock/pull/73 (etc)

### CODE REVIEW

**Comment by h-vetinari** [comment]
> doesn't need to be merged/shipped (just restores tests)

Should IMO definitely be merged, because the recipe at the moment should not be considered functional for pypy. If you don't increase the build number (and there are no major changes in the pinning causing the build hashes to change), no new packages will be uploaded.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please restart ci

**Comment by h-vetinari** [comment]
Ping @bollwyvl, this should still be merged at some point. :)

**Comment by bollwyvl** [comment]
tuns out this didn't actually _restore_ the tests, due to a selector... currently working this over on #128

**Pull request closed without merging**
