### PR TITLE
Release 6.4.0

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by Carreau** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
The [failure on CircleCI]( https://circleci.com/gh/conda-forge/ipython-feedstock/124 ) was networking related. Just went ahead and restarted it.

**Comment by jakirkham** [comment]
Looks like it is passing now. :)

**Pull request merged**
