### PR TITLE
MNT: Re-rendered with conda-build 3.18.11, conda-smithy 3.6.6, and co…

### PR DESCRIPTION
**Pull request by mkoeppe**
…nda-forge-pinning 2020.01.24

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Carreau** [comment]
That looks reasonable to me.  I bumped the build number as we are just rebuilding. 

Re Rendering did remove the build on Python 3.5; but my guess is Python 3.5 users will pull from previous builds.

I would advise to also look into updating sagelib to work with more recent IPython version. 6.0 was released closed to 3 years ago; current stable is 7.x and we are about to start working on 8.x.

**Comment by isuruf** [comment]
Thanks @Carreau. sagelib 9.0 released a month ago was the first release with python 3 support. They are going to remove python 2 support and update to IPython 7 in sagelib 10.0.

**Comment by Carreau** [comment]
> sagelib 9.0 released a month ago was the first release with python 3 support.

No problem, and congrats ! 

> They are going to remove python 2 support and update to IPython 7 in sagelib 10.0.

Hope you are going to enjoy the code base w/o Python 2. Please read some of https://python3statement.org/practicalities/ to drop Python 2 with minimal disruption.

All the test have passed; so let's try to merge to see if that works.

**Comment by mkoeppe** [comment]
Great. I think this closes #93

**Pull request merged**
