### PR TITLE
Release IPython 6.0.0

### PR DESCRIPTION
**Pull request by Carreau**
And re-render with smithy. 

Please make extra sure I did not get anything wrong for the Python 3 only case.

### CODE REVIEW

**Comment by minrk** [comment]
🎉

**Comment by takluyver** [comment]
Have we thought about how we will make further 5.x releases on conda-forge? Will we jump back and forth in this recipe? Or have a separate `ipython5-feedstock`?

**Comment by Carreau** [comment]
> Have we thought about how we will make further 5.x releases on conda-forge? Will we jump back and forth in this recipe? Or have a separate ipython5-feedstock?

No, not particularly. It scratched my mind yesterday.  It's pretty easy to `git checkout <tag> -- <files>` to get back. I don't know if feedstock can have built branches also.

**Comment by jakirkham** [comment]
The normal way to handle multiple active versions in a feedstock is to have multiple branches (much like other projects 😉). So we can add a branch on commit ( https://github.com/conda-forge/ipython-feedstock/commit/ec82b8154175f6ccea91e336e5dda30d374b837d ), which is the last commit on 5.x. Perhaps call it `v5.x` or similar. Then both branches can evolve separately. As we deploy changes from all branches on the main feedstock, there is nothing else that we will need to do. Examples of this include the [numpy]( https://github.com/conda-forge/numpy-feedstock ) and [python]( https://github.com/conda-forge/python-feedstock ) feedstocks where we do this already. Does that make sense?

**Comment by takluyver** [comment]
Thanks @jakirkham, I think that will work nicely for us.

**Pull request merged**
