### PR TITLE
ipython 8.0.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Carreau** [comment]
LGTM, 

We may want to have a 7.x branch at some point as I will likely do a few 7.x releases. 

Thanks !

**Review by Carreau — APPROVED** [review]

**Comment by bollwyvl** [comment]
>  Carreau added the automerge label 32 seconds ago

bold play!

> 7.x branch

[done](https://github.com/conda-forge/ipython-feedstock/tree/7.x). #157 adds it to the `abi_migrations`  for e.g. `py311` or whatever.

**Comment by Carreau** [comment]
> adds it to the `abi_migrations` for e.g. `py311` or whatever.

I have no clue what this is for, but thanks !

**Comment by bollwyvl** [comment]
> what this is for

it's so that the autotick bot knows which branches of the repo should get changes when a package needs to rebuilt for some specific upstream: in our case, we're sensitive to `{os, python implementation, python version}` but other things might have `{numpy}`or `{llvm}` in the mix.

what it _won't_ do is track the upstream branch or anything, so all 7.x PRs will be manual... but so are all of ours at this point. theoretically, if we removed the `migrating` stuff, we'd get bot PRs back... but it's actually been pretty handy, and the better play might be to dig into the guts of the bot and make it work.

**Pull request merged**
