### PR TITLE
require traitlets version >=4.2

### LINKED ISSUE #38: traitlets dependency requires lower version bound
meta.yaml is missing the minimum required version for traitlets. This can break ipython when upgrading from an older version.

Should be  traitlets>=4.2 according to ipython's setup.py.

### PR DESCRIPTION
**Pull request by croth1**
fixes #38

### CODE REVIEW

**Comment by croth1** [comment]
@conda-forge-admin please rerender

**Comment by croth1** [comment]
@conda-forge/core can you help me understanding the appveyor failure?

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
