### PR TITLE
Bump/7.0.1 tests

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Like #56 #57, this bumps to `7.0.1`. I've also:
- relaxed the `python >=3` in favor of relying on `skip`
- made the license tag SPDX-complian
- added all the optional test dependencies (well, not x11)
- run the tests

### CODE REVIEW

**Comment by bollwyvl** [comment]
(Oh, and i was getting fails with `test_history` on linux, so skipping for now...)

**Comment by blink1073** [comment]
Looks like that same test fails on osx.  Also, there is some subtlety about skip and noarch: https://conda-forge.org/docs/meta.html#building-noarch-packages

**Comment by bollwyvl** [comment]
Yerp, let's pretend I let the second invocation of the tests run for demonstration purposes, and not that i forgot the windows selector :blush: 

```py

  File "/home/conda/feedstock_root/build_artifacts/ipython_1538102512878/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.5/site-packages/IPython/core/tests/test_history.py", line 113, in test_history
    newhist[3]])
AssertionError: Lists differ: [(1, [51 chars]rn test'), (1, 3, "b='€Æ¾÷ß'"), (2, 1, 'z=5'), (2, 3, "k='p'")] != [(1, [51 chars]rn test'), (1, 3, "b='€Æ¾÷ß'"), (2, 3, "k='p'"), (2, 4, 'z=5')]

First differing element 3:
(2, 1, 'z=5')
(2, 3, "k='p'")

  [(1, 1, 'a=1'),
   (1, 2, 'def f():\n    test = 1\n    return test'),
   (1, 3, "b='€Æ¾÷ß'"),
-  (2, 1, 'z=5'),
-  (2, 3, "k='p'")]
?                 ^

+  (2, 3, "k='p'"),
?                 ^

+  (2, 4, 'z=5')]
```

**Comment by bollwyvl** [comment]
>  Also, there is some subtlety about skip and noarch:

Right, but we have plenty of platform-specific deps to worry about, other `noarch` dilemmas aside. I've recently been encountering issues like the one seen on appveyor where an output directory gets created with the full python version spec, `<` and all, [tries to get created on windows](https://ci.appveyor.com/project/conda-forge/ipython-feedstock/build/1.0.118/job/8sil6mbmso5u2q1j#L2200), but haven't dug much deeper:
```
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\bld\\ipython_1538087828414\\work_moved_ipython-7.0.1-py>=3_0_win-64_main_build_loop'
Command exited with code 1
```

**Comment by bollwyvl** [comment]
Here's a related report: https://github.com/conda/conda-build/issues/3105

**Comment by bollwyvl** [comment]
Well, that's OSX sorted!

**Comment by bollwyvl** [comment]
Hadn't seen this before:
```py
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/ipython_1538104060228/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.5/site-packages/pip/_internal/utils/outdated.py", line 90, in pip_version_check
    state = SelfCheckState(cache_dir=options.cache_dir)
  File "/home/conda/feedstock_root/build_artifacts/ipython_1538104060228/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.5/site-packages/pip/_internal/utils/outdated.py", line 25, in __init__
    self.statefile_path = os.path.join(cache_dir, "selfcheck.json")
  File "/home/conda/feedstock_root/build_artifacts/ipython_1538104060228/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/conda/feedstock_root/build_artifacts/ipython_1538104060228/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'bool'
```

**Comment by bollwyvl** [comment]
Great, now the long dark of the appveyor queue... really hope it passes there :P

**Comment by blink1073** [comment]
Ah curio is not available on Windows: https://github.com/conda-forge/curio-feedstock/blob/master/recipe/meta.yaml#L18

**Comment by blink1073** [comment]
cf https://github.com/dabeaz/curio/issues/210

**Comment by bollwyvl** [comment]
Well, shucks. I'll test on some real iron right now and get that selector
added and any test skips...

**Comment by bollwyvl** [comment]
Yep, tests worked the first time locally without any skips. :crossed_fingers:

**Comment by bollwyvl** [comment]
Added #44 while waiting...

**Comment by blink1073** [comment]
Why not add yourself and me as maintainers while we're at it?

**Comment by bollwyvl** [comment]
> Why not add yourself and me as maintainers while we're at it?

copy. killed the first appveyor job, since it would die anyway

**Comment by bollwyvl** [comment]
All green! Quick, someone press merge before it changes it's mind!

**Comment by Carreau** [comment]
> All green! Quick, someone press merge before it changes it's mind!

Damn if only you were maintainer...

**Comment by blink1073** [comment]
:tada:

**Pull request merged**
