### PR TITLE
IPython 7.27.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- will initially attempt full test with pypy37/win, but might still be busted

### CODE REVIEW

**Comment by bollwyvl** [comment]
Yep, win/pypy started hanging when trying to solve the (test, hopefully) env

**Comment by bollwyvl** [comment]
Buh, always with the drone. I've set automerge, hopefully it will finish sometime today... on other feedstocks, we've started moving the drone jobs to azure because of this...

**Comment by Carreau** [comment]
Oh ! The autobot does not submit PRs anymore ?

**Comment by bollwyvl** [comment]
> Oh ! The autobot does not submit PRs anymore ?

we might be in a weird spot because of the half-way completed migration... but the "wall of bot fail" on the status page says, unhelpfully:

```
We found a problem parsing the recipe for version '7.27.0': 

AssertionError('\n')

traceback:
  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py", line 506, in migrate
    cmeta = CondaMetaYAML(fp.read())
  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py", line 437, in __init__
    v, e = _parse_jinja2_variables(meta_yaml)
  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py", line 112, in _parse_jinja2_variables
    assert False, jinja2_data
```

It's probably the `migrating` thing... but we can't comment it out, yet.

**Comment by bollwyvl** [comment]
good job my little droney! you may live another day.

**Comment by bollwyvl** [comment]
(did have to rekick drone: https://cloud.drone.io/conda-forge/ipython-feedstock/170/1/1)

**Pull request merged**
