### PR TITLE
update recipe for IPython 5.5.0

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by takluyver** [comment]
The Appveyor failures may mean that the feedstock needs to be re-rendered.

**Comment by takluyver** [comment]
For some reason, Travis failed to upload the OSX packages after this was merged.

https://travis-ci.org/conda-forge/ipython-feedstock/builds/276545033

**Comment by jakirkham** [comment]
Need to cherry-pick commit ( https://github.com/conda-forge/ipython-feedstock/commit/631a3b505cf26d9c363a1ab18ff8b58c298b585b ) from `master` onto this branch. Would get rid of the `[ci skip]` and `[skip ci]` from the commit message.

**Comment by jakirkham** [comment]
Went ahead and did this in PR ( https://github.com/conda-forge/ipython-feedstock/pull/35 ).

**Comment by jakirkham** [comment]
These are now released.

**Pull request merged**
