### PR TITLE
Update to 6.3

### PR DESCRIPTION
**Pull request by takluyver**

### CODE REVIEW

**Comment by takluyver** [comment]
This will need a conda package of backcall - I've made a PR against the staging repo: https://github.com/conda-forge/staged-recipes/pull/5521

**Comment by ocefpaf** [comment]
@takluyver `backcall` is in the channel now.

BTW, please send the PRs from a fork to prevent the CIs from starting twice, wasting our most precious resource :smile:, and most important avoid a premature upload of the package before the merge.

**Comment by takluyver** [comment]
Oh, sorry. It's so convenient to edit it from the web interface. Anyway, in future I'll probably wait for the bot to do it.

**Comment by ocefpaf** [comment]
> Oh, sorry. It's so convenient to edit it from the web interface. Anyway, in future I'll probably wait for the bot to do it.

That is what I do, wait for the bot and change it using the web interface there.

**Comment by jakirkham** [comment]
There is a way to get web editing to work, but involves navigating to one's fork. It's a bit of a chore honestly. Though it can be done.

**Comment by takluyver** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
