### PR TITLE
IPython 7.20, restore pypy37 tests

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- restores tests, as #126
- update jedi pin

mad thanks to @Carreau for getting this one out.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Working on the pypy skips...

**Comment by bollwyvl** [comment]
Hm... there's a _lot_ of stuff failing on pypy (probably why we were skipping the tests entirely)... I may have to fall back to the "big skip," until we put some of this stuff under test upstream...

**Comment by bollwyvl** [comment]
actually making progress locally... the big blocker is the doctests... might just go ahead and clobber that real nasty-like...

**Comment by bollwyvl** [comment]
I gave up trying to trick the 50+ erroring `core` doctests into being skipped, so I'm just skipping the entire `core` group on pypy :crying_cat_face: . This is skipping ~500 tests... but leaves some ~300 tests. Better'n :zero:, i suppose!

**Comment by Carreau** [comment]
Yeah, the doctest will likely go away once we support 3.10; as nose is not compatible 3.10.

**Comment by bollwyvl** [comment]
Lil' bit of :snowflake:, but I'll take it!

**Comment by bollwyvl** [comment]
All up:
```
linux-64/ipython-7.20.0-py37h2b89940_0.tar.bz2
linux-64/ipython-7.20.0-py37h888b3d9_0.tar.bz2
linux-64/ipython-7.20.0-py38h81c977d_0.tar.bz2
linux-64/ipython-7.20.0-py39hef51801_0.tar.bz2
linux-aarch64/ipython-7.20.0-py37h9e1f083_0.tar.bz2
linux-aarch64/ipython-7.20.0-py37hc16ab0a_0.tar.bz2
linux-aarch64/ipython-7.20.0-py38hd825144_0.tar.bz2
linux-aarch64/ipython-7.20.0-py39hef158d4_0.tar.bz2
linux-ppc64le/ipython-7.20.0-py37h7b46356_0.tar.bz2
linux-ppc64le/ipython-7.20.0-py37hfeca116_0.tar.bz2
linux-ppc64le/ipython-7.20.0-py38h3c958fc_0.tar.bz2
linux-ppc64le/ipython-7.20.0-py39h0de2273_0.tar.bz2
osx-64/ipython-7.20.0-py37h5b6bc8d_0.tar.bz2
osx-64/ipython-7.20.0-py37he01cfaa_0.tar.bz2
osx-64/ipython-7.20.0-py38h9bb44b7_0.tar.bz2
osx-64/ipython-7.20.0-py39h71a6800_0.tar.bz2
osx-arm64/ipython-7.20.0-py38h2cb4d76_0.tar.bz2
osx-arm64/ipython-7.20.0-py39h32adebf_0.tar.bz2
win-64/ipython-7.20.0-py37heaed05f_0.tar.bz2
win-64/ipython-7.20.0-py38hc5df569_0.tar.bz2
win-64/ipython-7.20.0-py39h832f523_0.tar.bz2 
```

**Pull request merged**
